"""App-wide constants (non-config)."""

from app.constants.messages import (
    ERROR_MESSAGE_AI_CHAT_NOT_CONFIGURED,
    ERROR_MESSAGE_AI_NOT_CONFIGURED,
    ERROR_MESSAGE_EMAIL_ALREADY_REGISTERED,
    ERROR_MESSAGE_FILE_NOT_FOUND,
    ERROR_MESSAGE_GEOMETRY_COORDS_LNG_LAT,
    ERROR_MESSAGE_GEOMETRY_COORDS_NUMBERS,
    ERROR_MESSAGE_GEOMETRY_TYPE_POINT,
    ERROR_MESSAGE_INCORRECT_EMAIL_OR_PASSWORD,
    ERROR_MESSAGE_MASTER_PLAN_NOT_FOUND,
    ERROR_MESSAGE_NO_RESPONSE_FROM_MODEL,
    ERROR_MESSAGE_NOT_AUTHENTICATED,
    ERROR_MESSAGE_OBJECT_NOT_FOUND,
    ERROR_MESSAGE_PROJECT_NOT_FOUND,
)

# Max objects to include in AI context to avoid token overflow
MAX_OBJECTS_IN_AI_CONTEXT = 500

__all__ = [
    "ERROR_MESSAGE_AI_CHAT_NOT_CONFIGURED",
    "ERROR_MESSAGE_AI_NOT_CONFIGURED",
    "ERROR_MESSAGE_EMAIL_ALREADY_REGISTERED",
    "ERROR_MESSAGE_FILE_NOT_FOUND",
    "ERROR_MESSAGE_GEOMETRY_COORDS_LNG_LAT",
    "ERROR_MESSAGE_GEOMETRY_COORDS_NUMBERS",
    "ERROR_MESSAGE_GEOMETRY_TYPE_POINT",
    "ERROR_MESSAGE_INCORRECT_EMAIL_OR_PASSWORD",
    "ERROR_MESSAGE_MASTER_PLAN_NOT_FOUND",
    "ERROR_MESSAGE_NO_RESPONSE_FROM_MODEL",
    "ERROR_MESSAGE_NOT_AUTHENTICATED",
    "ERROR_MESSAGE_OBJECT_NOT_FOUND",
    "ERROR_MESSAGE_PROJECT_NOT_FOUND",
    "MAX_OBJECTS_IN_AI_CONTEXT",
]
